package co.com.fcv.training.citas.adapter.persistence;

import jakarta.persistence.*;
import java.time.*;

@Entity @Table(name="locations") class LocationEntity { @Id Short id; String code; String name; boolean active; protected LocationEntity(){} }
@Entity @Table(name="specialties") class SpecialtyEntity { @Id Short id; String code; String name; @Column(name="appointment_duration_minutes") Short duration; @Column(name="is_general") boolean general; @Column(name="requires_admin_approval") boolean approvalRequired; boolean active; protected SpecialtyEntity(){} }
@Entity @Table(name="professionals") class ProfessionalEntity { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="user_id") Long userId; @Column(name="professional_code") String code; @Column(name="license_number") String license; boolean active; protected ProfessionalEntity(){} }
@Entity @Table(name="availability_blocks") class AvailabilityBlockEntity { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="professional_id") Long professionalId; @Column(name="location_id") Short locationId; @Column(name="available_date") LocalDate date; @Column(name="start_time") LocalTime start; @Column(name="end_time") LocalTime end; boolean active=true; protected AvailabilityBlockEntity(){} }
@Entity @Table(name="professional_slots") class ProfessionalSlotEntity { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="availability_block_id") Long blockId; @Column(name="start_at") LocalDateTime startAt; @Column(name="end_at") LocalDateTime endAt; @Column(name="appointment_id") Long appointmentId; protected ProfessionalSlotEntity(){} }
@Entity @Table(name="appointments") class AppointmentEntity { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="patient_user_id") Long patientId; @Column(name="professional_id") Long professionalId; @Column(name="location_id") Short locationId; @Column(name="specialty_id") Short specialtyId; @Column(name="status_id") Short statusId; String reason; @Column(name="scheduled_start_at") LocalDateTime startAt; @Column(name="scheduled_end_at") LocalDateTime endAt; @Column(name="created_by_user_id") Long createdBy; @Column(name="approved_by_user_id") Long approvedBy; @Column(name="approved_at") LocalDateTime approvedAt; @Column(name="created_at") Instant createdAt; protected AppointmentEntity(){} }
@Entity @Table(name="appointment_statuses") class AppointmentStatusEntity { @Id Short id; String code; String name; @Column(name="is_terminal") boolean terminal; protected AppointmentStatusEntity(){} }
@Entity @Table(name="appointment_status_history") class AppointmentHistoryEntity { @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id; @Column(name="appointment_id") Long appointmentId; @Column(name="status_id") Short statusId; @Column(name="changed_by_user_id") Long actorId; @Column(name="change_source") String source; String reason; @Column(name="changed_at") Instant changedAt; protected AppointmentHistoryEntity(){} }
